# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('personal_website', models.URLField()),
                ('image_file', models.ImageField(upload_to=b'')),
                ('german_skills', models.CharField(choices=[(b'NO', b'None'), (b'SOME', b'Some'), (b'YES', b'Yes')], default=b'NO', max_length=4)),
            ],
        ),
    ]
