# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_opportunity_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image_file',
            new_name='image',
        ),
    ]
